name: SwiftlyCrafted
main: me.Chris.SwiftlyCrafted.main
version: 1.7.9 - Alpha plugin 
author: SwiftlyCraftedDevs
description: The main plugin for SwiftlyCrafted.

commands:
  rank:
    description: Creates a rank for a player.
