name: SwiftlyCrafted
main: me.Chris.SwiftlyCrafted.Hub.main
version: 1.7.9  
author: SwiftlyCraftedDevs
description: The main plugin for SwiftlyCrafted.

commands:
  rank:
    description: Creates a rank for a player.
  swifty:
    description: Swifties
  spawn:
    description: Yep.
